export const GenereList = [
  { genere: "Action", isChecked: false },
  { genere: "Adventure", isChecked: false },
  { genere: "Animation", isChecked: false },
  { genere: "Biography", isChecked: false },
  { genere: "Classic", isChecked: false },
  { genere: "Comedy", isChecked: false },
  { genere: "Crime", isChecked: false },
  { genere: "Drama", isChecked: false },
  { genere: "Family", isChecked: false },
  { genere: "Fantasy", isChecked: false },
  { genere: "History", isChecked: false },
  { genere: "Horror", isChecked: false },
  { genere: "Musical", isChecked: false },
  { genere: "Mystery", isChecked: false },
  { genere: "Period", isChecked: false },
  { genere: "Psychological", isChecked: false },
  { genere: "Romance", isChecked: false },
  { genere: "Sci-Fi", isChecked: false },
  { genere: "Social", isChecked: false },
  { genere: "Sports", isChecked: false },
  { genere: "Suspense", isChecked: false },
  { genere: "Thriller", isChecked: false },
  { genere: "War", isChecked: false }
];
